services:
  - type: web
    name: UserTransactionAPI
    env: node
    region: oregon
    buildCommand: "npm install"
    startCommand: "node app.js"
    plan: free
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: DB_NAME
        sync: false